# Generated by Django 4.1.7 on 2023-04-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=15, verbose_name='first name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('reason', models.CharField(choices=[('Registration', 'Registration'), ('Order', 'Order'), ('Payment', 'Payment'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='reason')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
