# Generated by Django 4.1.7 on 2023-04-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='is checked'),
        ),
    ]
