# Generated by Django 4.1.7 on 2023-04-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_full_name_contact_name_contact_is_checked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
