# Generated by Django 4.1.7 on 2023-04-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_amount', models.IntegerField(verbose_name='amount')),
                ('order_name', models.CharField(max_length=200, verbose_name='order name')),
                ('order_desc', models.TextField(verbose_name='order description')),
                ('is_payed', models.BooleanField(default=False, verbose_name='is payed')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
