# Generated by Django 4.1.7 on 2023-04-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orderrequest_costumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='order',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='costumer',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderRequest',
        ),
    ]
