# Generated by Django 4.1.7 on 2023-04-17 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_delete_contact_remove_order_costumer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, verbose_name='first name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('reason', models.CharField(default='Other', max_length=100, verbose_name='reason')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_checked', models.BooleanField(default=False, verbose_name='is_checked')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_img')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
                ('desc', models.TextField(verbose_name='description')),
                ('type', models.CharField(blank=True, choices=[('custom', 'custom'), ('standart', 'standart')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('link', models.CharField(max_length=200, verbose_name='link')),
                ('review', models.TextField(verbose_name='review')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('desc', models.TextField(verbose_name='Description')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='is ordered')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payed_amount', models.IntegerField(verbose_name='price')),
                ('is_payed', models.BooleanField(default=False, verbose_name='is_payed')),
                ('is_done', models.BooleanField(default=False, verbose_name='is_done')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
