# Generated by Django 4.1.7 on 2023-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='deposit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payed_amount',
            field=models.IntegerField(verbose_name='amount'),
        ),
    ]
