# Generated by Django 4.1.7 on 2023-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_order_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='deposit'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_payed',
            field=models.BooleanField(default=False, verbose_name='deposit_payed'),
        ),
    ]
