# Generated by Django 4.1.7 on 2023-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payed_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payed amount'),
        ),
    ]
