# Generated by Django 4.1.7 on 2023-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_payed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_access',
            field=models.BooleanField(default=False, verbose_name='pay_access'),
        ),
    ]
